### ISSUE TITLE
Admin Control suggest options

### ISSUE THREAD

**Issue by Clusterpuck** [Clusterpuck/QuantumDelivery#270]
For Edit and Delete, will be much better to use an autocomplete populated with the data to choose from. For example for customer can use this:

              <Autocomplete
                disablePortal
                id="Customers"
                size="small"
                options={customers || []}
                loading={loadingCustomers}
                getOptionLabel={(option) => `${option.name} ${option.phone}`}
                value={selectedCustomer}
                onChange={handleCustomerChange}
                renderInput={(params) => (
                  <TextField {...params} label="Select Customer" />
                )}
              />

**Comment by ameliefishr** [comment]
was planning to add some kind of search/drop down over the weekend to add the ability to search by name, would autocomplete do this?

**Comment by ameliefishr** [comment]
closing as I made another issue that includes this
