### ISSUE TITLE
Performance View Routes

### ISSUE THREAD

**Issue by Clusterpuck** [Clusterpuck/QuantumDelivery#284]
Look into lazing loading accordion. 
Review performance issues on those pages

**Comment by Sonny6155** [comment]
More details:
"View Routes" page appears to load everything accordion on refresh, which results in poor performance on weaker computers or poor network. The page remains mostly unresponsive or stutters until the full page is loaded. Presumably, most of the time and size is taken up by MapBox loading. The suggestion is only load the route details as needed to improve the average user experience.

As of 2024-09-27 11:19AM, this downloads 9.57MB across 214 requests which takes 1.08min on my machine using Firefox. On a Agam's machine, this produces 12.4MB and 242 requests over across 15.30sec on Chrome. In comparison, the "All Orders" page only downloads 132kB across 1.58s and 6 requests.
